server:
  port: 8080

spring:
  config:
    import: secrets.properties

  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQLUSER}
    password: ${MYSQLPASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
        ddl-auto: update

    properties:
      hibernate:
        format_sql: true